### ISSUE TITLE
Feedback for “Demo”

### ISSUE THREAD

**Issue by Aggror** [simonkarman/krmx#1]
page https://simonkarman.github.io/krmx/getting-started/demo

Create a Krmx server 
touch server.ts (mocht je het niet hebben: npm install touch-cli -g)

404
Learn more about the [Krmx server](https://simonkarman.github.io/krmx/server)
Learn more about the [Krmx clients](https://simonkarman.github.io/krmx/clients)

**Comment by simonkarman** [comment]
Thanks @Aggror for your feedback! Have have updated the docs on the demo accordingly in [#c68eb48441d452841f2f3e0fd7b24cae44dbbd39](https://github.com/simonkarman/krmx/commit/c68eb48441d452841f2f3e0fd7b24cae44dbbd39)
